fs 				= require 'fs'
{log} 			= require 'util'
{spawn, exec} 	= require 'child_process'

task 'run', 'run the webserver', ->
	log 'starting webserver'

	out = (error, stdout, stderr) ->
		console.log(stdout)
		console.error(stderr)

	exec 'cd src; coffee ../lib/serve.coffee', out
	exec 'open http://127.0.0.1:8000/'